#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Streamlit app for Image Captioning
Uses trained model (final_image_captioning_model.h5),
tokenizer_2.pkl, and config.pkl (for max_length, vocab_size).
"""

import os
import pickle
import numpy as np
from PIL import Image
import streamlit as st
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model, Model
from tensorflow.keras.preprocessing.sequence import pad_sequences

# ---------------------------
# Paths
# ---------------------------
WORKING_DIR = r"C:\Users\HP\Downloads\image_captioning_prroject\flickr\working"
MODEL_PATH = os.path.join(WORKING_DIR, "final_image_captioning_model.h5")
TOKENIZER_PATH = os.path.join(WORKING_DIR, "tokenizer_2.pkl")  # Updated tokenizer
CONFIG_PATH = os.path.join(WORKING_DIR, "config.pkl")

# ---------------------------
# Load resources
# ---------------------------
@st.cache_resource(show_spinner=True)
def load_resources():
    # Load tokenizer
    with open(TOKENIZER_PATH, "rb") as f:
        tokenizer = pickle.load(f)
    # Load config
    with open(CONFIG_PATH, "rb") as f:
        config = pickle.load(f)
    max_length = config.get("max_length", 34)
    vocab_size = config.get("vocab_size", len(tokenizer.word_index) + 1)
    # Load trained captioning model
    model = load_model(MODEL_PATH, compile=False)
    # Load VGG16 feature extractor
    vgg = VGG16(weights="imagenet")
    vgg = Model(inputs=vgg.inputs, outputs=vgg.layers[-2].output)
    return model, tokenizer, vgg, max_length, vocab_size

# ---------------------------
# Feature extraction
# ---------------------------
def extract_features(image_pil, vgg_model):
    img = image_pil.convert("RGB").resize((224, 224))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)
    feature = vgg_model.predict(img_array, verbose=0)
    return feature  # shape (1, 4096)

# ---------------------------
# Word mapping
# ---------------------------
def idx_to_word(integer, tokenizer):
    for word, index in tokenizer.word_index.items():
        if index == integer:
            return word
    return None

# ---------------------------
# Caption prediction
# ---------------------------
def predict_caption(model, image_feature, tokenizer, max_length):
    in_text = "<start>"
    for _ in range(max_length):
        sequence = tokenizer.texts_to_sequences([in_text])[0]
        sequence = pad_sequences([sequence], maxlen=max_length)
        yhat = model.predict([image_feature, sequence], verbose=0)
        yhat = np.argmax(yhat)
        word = idx_to_word(yhat, tokenizer)
        if word is None:
            break
        in_text += " " + word
        if word == "<end>":
            break
    caption = in_text.replace("<start>", "").replace("<end>", "").strip()
    return caption

# ---------------------------
# Streamlit UI
# ---------------------------
st.set_page_config(page_title="Image Captioning App", layout="centered")
st.title(" Image Caption Generator")
st.write("Upload an image and get a caption generated by your trained model.")

# Load model and tokenizer
with st.spinner("Loading model and tokenizer..."):
    model, tokenizer, vgg, max_length, vocab_size = load_resources()
st.success("Model and tokenizer loaded successfully ")

# File uploader
uploaded_file = st.file_uploader("Upload an image (JPG or PNG)", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image_pil = Image.open(uploaded_file)
    st.image(image_pil, caption="Uploaded Image", use_column_width=True)
    
    with st.spinner("Generating caption..."):
        feature = extract_features(image_pil, vgg)
        caption = predict_caption(model, feature, tokenizer, max_length)
    
    st.subheader(" Generated Caption:")
    st.markdown(f"**{caption}**")

    st.download_button("Download Caption", caption.encode("utf-8"), file_name="caption.txt")

st.markdown("---")
st.info("Make sure `final_image_captioning_model.h5`, `tokenizer_2.pkl`, and `config.pkl` are in the working directory.")
